"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import React from "react";
import styled from "styled-components";

const NavigationBar = () => {
  return (
    <NavContainer>
      <NavButton>
        {/* <Icon src="/home-icon.svg" alt="Home" /> */}
        <Link href={"/"}>Home</Link>
      </NavButton>

      <NavButton>
        {/* <Icon src="/favorites-icon.svg" alt="Favorites" /> */}
        <Link href={"/favorites"}>Favorites</Link>
      </NavButton>
    </NavContainer>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}

const NavContainer = styled.nav`
  width: 100%;
  background-color: #333;
  color: white;
  display: flex;
  justify-content: space-around;
  align-items: center;

  @media (max-width: 768px) {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    display: flex;
    flex-direction: column;
  }
`;

const NavButton = styled.div`
  text-decoration: none;
  color: inherit;
  text-align: center;
  flex-grow: 1;
  padding: 0.5rem 0;
  transition: background-color 0.3s ease;

  @media (max-width: 768px) {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  &:hover {
    background-color: #555;
  }
`;

const Icon = styled.img`
  width: 24px;
  height: 24px;
  margin-right: 0.5rem;
`;
